[Distribution]
Distribution=fedora
Release=44
Architecture=x86-64

[Output]
Format=directory
Output=rootfs

[Content]
Bootable=no
Packages=kernel,grub2-pc,grub2-efi-x64,grub2-efi-x64-modules,efibootmgr,ca-certificates,cloud-init,curl,NetworkManager,openssh-server,sudo
