[Distribution]
Distribution=ubuntu
Release=resolute
Architecture=x86-64

[Output]
Format=directory
Output=rootfs

[Content]
Bootable=no
Packages=linux-generic,initramfs-tools,systemd-sysv,grub-pc,grub-efi-amd64-bin,efibootmgr,ca-certificates,cloud-init,curl,netplan.io,openssh-server,sudo
